
services:
  nginx:
    build: 
      context: ./nginx/
      dockerfile: nginx.dockerfile
    hostname: matthewhill.click
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - encrypt:/letsencrypt
      - challenge:/var/www/certbot
      - static:/static
    depends_on:
      - certbot
    entrypoint: ["bash", "-c"]
    command: ["nginx -c /etc/nginx/nginx.conf -g 'daemon off;' & /var/controller.sh"]

  certbot:
    build: 
      context: ./certbot/
      dockerfile: certbot.dockerfile
    volumes:
      - encrypt:/etc/letsencrypt
      - challenge:/var/www/certbot  

  gunicorn:
    build:
      context: ./gunicorn
      dockerfile: gunicorn.dockerfile
    expose:
      - 8000
    entrypoint: gunicorn
    command: ["wsgi:app", "--chdir", "/var/www/", "-c", "gunicorn.config.py"]

volumes:
  challenge:
  encrypt:
  static: 

