
services:
  http:
    image: amazingplum/http:latest
    build: 
      context: https://github.com/amazingplum53/docker_compose.git#master:.docker
      dockerfile: nginx.dockerfile
    hostname: matthewhill.click
    ports:
      - "80:80"
      - "443:443"
      
  gunicorn:
    image: amazingplum/gunicorn:latest
    build:
      context: https://github.com/amazingplum53/docker_compose.git#master:.docker
      dockerfile: gunicorn.dockerfile

