apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: challenge
  name: challenge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
