apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: encrypt
  name: encrypt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
