apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/portfolio-default: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - args:
            - nginx -c /etc/nginx/nginx.conf -g 'daemon off;' & /var/controller.sh
          command:
            - bash
            - -c
          image: nginx
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "52428800"
          volumeMounts:
            - mountPath: /letsencrypt
              name: encrypt
            - mountPath: /var/www/certbot
              name: challenge
            - mountPath: /static
              name: static
      hostname: matthewhill.click
      restartPolicy: Always
      volumes:
        - name: encrypt
          persistentVolumeClaim:
            claimName: encrypt
        - name: challenge
          persistentVolumeClaim:
            claimName: challenge
        - name: static
          persistentVolumeClaim:
            claimName: static
