
apiVersion: apps/v1
kind: Deployment
metadata:
  name: https
  labels: 
    app: https
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https
  template:
    metadata:
      labels:
        app: https
    spec:
      initContainers:
      - name: certbot
        image: amazingplum/docker_compose-certbot
        command: ["bash", "-c"]
        args: ["/var/renew.sh"]
        volumeMounts:
        - name: challenge
          mountPath: /var/www/certbot 
        - name: encrypt
          mountPath: /letsencrypt
      containers:
      - name: https
        image: amazingplum/docker_compose-nginx
        command: ["bash", "-c"]
        args: ["nginx -c /etc/nginx/https.conf -g 'daemon off;'"]
        ports:
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: encrypt
          mountPath: /letsencrypt
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: encrypt
        persistentVolumeClaim:
          claimName: encrypt
      - name: challenge
        persistentVolumeClaim:
          claimName: challenge
