apiVersion: apps/v1
kind: Deployment
metadata:
  #labels:
    #io.kompose.service: gunicorn
  name: gunicorn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gunicorn
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/portfolio-default: "true"
        io.kompose.service: gunicorn
    spec:
      containers:
        - args:
            - portfolio.wsgi
            - -c
            - gunicorn.config.py
          command:
            - gunicorn
          image: gunicorn
          name: gunicorn
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "209715200"
          volumeMounts:
            - mountPath: /run/secrets
              name: portfolio.env
              subPath: portfolio.env
            - mountPath: /var/www/portfolio/static
              name: static
      restartPolicy: Always
      volumes:
        - name: portfolio.env
          secret:
            items:
              - key: portfolio.env
                path: portfolio.env
            secretName: portfolio.env
        - name: static
          persistentVolumeClaim:
            claimName: static
