apiVersion: v1
data:
  portfolio.env: ew0KICAgICJTRUNSRVRfS0VZIjogInk2NXojeGglc3lxdG5rbndrLXpAJnM1cV54MWVjcWZ2JCFpNF90MDR0NDYzbHB0bXJyIiwNCiAgICAiU0VUVElOR1MiOiAidGVzdCINCn0=
kind: Secret
metadata:
  labels:
    io.kompose.service: portfolio.env
  name: portfolio.env
type: Opaque
