apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: challenge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: encrypt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi