kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: encrypt
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard-rwx
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: encrypt

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: encrypt
  labels:
    type: encrypt
spec:
  storageClassName: standard-rwx
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io