
apiVersion: batch/v1
kind: Job
metadata:
  name: certificate-renewal
spec:
  template:
    metadata:
      name: certbot-challenge
    spec:
      containers:
        - name: certbot
          image: amazingplum/docker_compose-certbot
          volumeMounts:
            - name: challenge
              mountPath: /var/www/certbot 
            - name: encrypt
              mountPath: /letsencrypt
      restartPolicy: Never
      volumes:
      - name: encrypt
        persistentVolumeClaim:
          claimName: encrypt
      - name: challenge
        persistentVolumeClaim:
          claimName: challenge
  backoffLimit: 0
