
services:
  http:
    image: amazingplum/http:latest
    build: 
      context: https://github.com/amazingplum53/template-site.git#master:.docker
      dockerfile: nginx.dockerfile
    hostname: matthewhill.click
      
  gunicorn:
    image: amazingplum/gunicorn:latest
    build:
      context: https://github.com/amazingplum53/template-site.git#master:.docker
      dockerfile: gunicorn.dockerfile

