kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: tls-gateway
spec:
  gatewayClassName: gke-17-regional-external-managed
  listeners:
  - name: http
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        networking.gke.io/cert-manager-certs: matthewhill
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: All

---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http
spec:
  parentRefs:
  - name: tls-gateway
  hostnames:
  - "matthewhill.click"
  rules:
  - backendRefs:
    - name: nginx
      port: 80