kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: gateway
spec:
  gatewayClassName: gke-17-regional-external-managed
  listeners:
  - name: port-forward
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        networking.gke.io/cert-manager-certs: matthewhill
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: All

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: port-forward
spec:
  parentRefs:
  - name: gateway
  hostnames:
  - "matthewhill.click"
  rules:
    backendRefs:
    - name: nginx
      port: 80