apiVersion: v1
kind: Service
metadata:
  name: nginx 
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec: 
  ports:
  - name: http
    port: 80 
    protocol: TCP
    targetPort: 80
  selector:
    app: http