apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: http-gateway
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    protocol: HTTP
    port: 443


---


apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http
spec:
  parentRefs:
  - kind: Gateway
    name: http-gateway
  hostnames:
  - "matthewhill.click"
  rules:
  - backendRefs:
    - name: http
      port: 80


---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: https
spec:
  parentRefs:
  - kind: Gateway
    name: http-gateway
  hostnames:
  - "matthewhill.click"
  rules:
  - backendRefs:
    - name: https
      port: 443

